# Generated by Django 6.0.4 on 2026-04-17 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approval_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfiller',
            field=models.ForeignKey(blank=True, help_text='Who fulfills the order if drop-shipped', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_fulfilled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='is_credit_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_dropship',
            field=models.BooleanField(default=False, help_text='Fulfilled by upstream supplier'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('b2c', 'Business to Customer'), ('b2b', 'Business to Business'), ('supply_chain', 'Supply Chain'), ('farm_to_company', 'Farm to Company')], default='b2c', max_length=20),
        ),
    ]
