# Generated by Django 6.0.4 on 2026-04-19 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0001_initial'),
        ('orders', '0002_order_approval_status_order_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='affiliate',
            field=models.ForeignKey(blank=True, help_text='Affiliate who generated this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch for traceability', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='aggregation.batch'),
        ),
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.CharField(choices=[('wholesale', 'Wholesale'), ('retail', 'Retail'), ('direct', 'Direct to Consumer'), ('institutional', 'Institutional'), ('affiliate', 'Affiliate')], default='retail', max_length=20),
        ),
    ]
