# Generated by Django 6.0.4 on 2026-04-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='owner_type',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('company', 'Company'), ('depot', 'Depot'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer')], max_length=20),
        ),
    ]
