# Generated by Django 6.0.4 on 2026-04-19 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aggregation', '0001_initial'),
        ('production', '0002_harvestforecast_supplycontract'),
        ('products', '0002_alter_inventory_owner_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingFacility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('mill', 'Mill'), ('factory', 'Factory'), ('packhouse', 'Packhouse'), ('abattoir', 'Abattoir'), ('dairy', 'Dairy Plant'), ('cold_storage', 'Cold Storage'), ('other', 'Other')], default='factory', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('capacity_kg_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_facilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'processing facilities',
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_number', models.CharField(max_length=30, unique=True)),
                ('input_quantity_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('output_quantity_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('waste_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='processing.processingfacility')),
                ('input_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_jobs', to='aggregation.batch')),
                ('input_crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.crop')),
                ('output_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_jobs', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost_type', models.CharField(choices=[('labor', 'Labor'), ('energy', 'Energy'), ('packaging', 'Packaging'), ('chemicals', 'Chemicals/Additives'), ('equipment', 'Equipment'), ('overhead', 'Overhead'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='processing.processingjob')),
            ],
        ),
        migrations.CreateModel(
            name='YieldRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('output_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('waste_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('yield_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yield_record', to='processing.processingjob')),
            ],
        ),
    ]
