# Generated by Django 6.0.4 on 2026-04-19 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0002_harvestforecast_supplycontract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregationCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('center_type', models.CharField(choices=[('collection_point', 'Collection Point'), ('buying_center', 'Buying Center'), ('cooperative', 'Cooperative'), ('warehouse', 'Warehouse')], default='collection_point', max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('capacity_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_stock_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_centers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=30, unique=True)),
                ('total_quantity_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quality_grade', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('aggregating', 'Aggregating'), ('complete', 'Complete'), ('processing', 'Sent to Processing'), ('dispatched', 'Dispatched')], default='created', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='aggregation.aggregationcenter')),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='production.crop')),
            ],
            options={
                'verbose_name_plural': 'batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntakeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Price paid per kg to farmer', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intakes', to='aggregation.batch')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='aggregation.aggregationcenter')),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intakes', to='production.crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_records', to=settings.AUTH_USER_MODEL)),
                ('harvest_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intakes', to='production.harvestrecord')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intakes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.CharField(choices=[('premium', 'Premium'), ('grade_a', 'Grade A'), ('grade_b', 'Grade B'), ('grade_c', 'Grade C'), ('rejected', 'Rejected')], default='grade_a', max_length=20)),
                ('moisture_content', models.DecimalField(decimal_places=2, default=0, help_text='Percentage', max_digits=5)),
                ('impurity_pct', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of impurities', max_digits=5)),
                ('size_uniformity', models.CharField(blank=True, max_length=50)),
                ('color_assessment', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_assessments', to=settings.AUTH_USER_MODEL)),
                ('intake', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_assessment', to='aggregation.intakerecord')),
            ],
        ),
    ]
