# Generated by Django 6.0.4 on 2026-04-19 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_inventory_owner_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_type', models.CharField(choices=[('sales', 'Sales Analytics'), ('inventory', 'Inventory Analytics'), ('supply_chain', 'Supply Chain Analytics'), ('financial', 'Financial Analytics'), ('production', 'Production Analytics'), ('demand', 'Demand Analytics')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('data', models.JSONField(default=dict, help_text='Snapshot data as JSON')),
                ('insights', models.JSONField(blank=True, default=list, help_text='Generated insights')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100)),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('predicted_demand_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('predicted_demand_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, help_text='Confidence score 0-100', max_digits=5)),
                ('actual_demand_qty', models.DecimalField(decimal_places=2, default=0, help_text='Filled in after period ends', max_digits=12)),
                ('data_sources', models.JSONField(blank=True, default=list, help_text='Sources used for prediction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to='products.product')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('bulk_discount', 'Bulk Discount'), ('seasonal', 'Seasonal Adjustment'), ('dynamic', 'Dynamic (Supply/Demand)'), ('promotional', 'Promotional'), ('tiered', 'Tiered Pricing')], max_length=20)),
                ('conditions', models.JSONField(default=dict, help_text='Rule conditions (e.g. min_qty, date_range)')),
                ('price_modifier', models.DecimalField(decimal_places=4, default=1.0, help_text='Multiplier: 0.9 = 10% off, 1.1 = 10% markup', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='products.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_rules', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyDemandMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100)),
                ('supply_available_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('demand_forecast_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gap_kg', models.DecimalField(decimal_places=2, default=0, help_text='Positive = surplus, negative = shortage', max_digits=12)),
                ('recommended_action', models.CharField(choices=[('increase_supply', 'Increase Supply'), ('reduce_supply', 'Reduce Supply'), ('maintain', 'Maintain Current Levels'), ('redistribute', 'Redistribute Stock'), ('price_adjust', 'Adjust Pricing')], default='maintain', max_length=20)),
                ('price_suggestion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_demand_matches', to='products.product')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
    ]
