# Generated by Django 6.0.4 on 2026-04-19 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0001_initial'),
        ('logistics', '0001_initial'),
        ('products', '0002_alter_inventory_owner_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_time', models.DateTimeField()),
                ('delivery_time', models.DateTimeField()),
                ('route', models.TextField(blank=True, help_text='Route description or waypoints')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='logistics.shipment')),
            ],
            options={
                'ordering': ['-pickup_time'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('storage_type', models.CharField(choices=[('dry', 'Dry Storage'), ('cold', 'Cold Storage'), ('frozen', 'Frozen Storage'), ('general', 'General')], default='general', max_length=20)),
                ('capacity_kg', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('current_stock_kg', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity_units', models.PositiveIntegerField(default=0)),
                ('location_in_warehouse', models.CharField(blank=True, help_text='Aisle/shelf/bin', max_length=100)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_stocks', to='aggregation.batch')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_stocks', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='logistics.warehouse')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
