# Generated by Django 6.0.4 on 2026-04-17 08:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(blank=True, help_text='e.g. cereal, legume, fruit, vegetable', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('growing_season', models.CharField(blank=True, max_length=100)),
                ('avg_yield_per_acre', models.DecimalField(decimal_places=2, default=0, help_text='kg per acre', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LivestockRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('animal_type', models.CharField(choices=[('cattle', 'Cattle'), ('goats', 'Goats'), ('sheep', 'Sheep'), ('pigs', 'Pigs'), ('poultry', 'Poultry'), ('fish', 'Fish'), ('rabbits', 'Rabbits'), ('other', 'Other')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('count', models.PositiveIntegerField(default=0)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('quarantine', 'Quarantine'), ('deceased', 'Deceased')], default='healthy', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['animal_type'],
            },
        ),
        migrations.CreateModel(
            name='PlantingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(blank=True, help_text='Name/identifier of the field', max_length=255)),
                ('area_acres', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planted', 'Planted'), ('growing', 'Growing'), ('ready_to_harvest', 'Ready to Harvest'), ('harvested', 'Harvested'), ('failed', 'Failed')], default='planted', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planting_records', to='production.crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planting_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-planting_date'],
            },
        ),
        migrations.CreateModel(
            name='HarvestRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('harvest_date', models.DateField()),
                ('yield_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quality_grade', models.CharField(choices=[('premium', 'Premium'), ('grade_a', 'Grade A'), ('grade_b', 'Grade B'), ('grade_c', 'Grade C'), ('rejected', 'Rejected')], default='grade_a', max_length=20)),
                ('storage_location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_records', to=settings.AUTH_USER_MODEL)),
                ('planting_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='production.plantingrecord')),
            ],
            options={
                'ordering': ['-harvest_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_description', models.CharField(max_length=500)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('fulfilled', 'Fulfilled')], default='open', max_length=20)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_offers_made', to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_offers_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
