# Generated by Django 6.0.4 on 2026-04-19 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimated_yield_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, help_text='Confidence 0-100', max_digits=5)),
                ('forecast_date', models.DateField()),
                ('methodology', models.CharField(blank=True, help_text='How the forecast was generated', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_forecasts', to=settings.AUTH_USER_MODEL)),
                ('planting_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='production.plantingrecord')),
            ],
            options={
                'ordering': ['-forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplyContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=30, unique=True)),
                ('committed_quantity_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivered_quantity_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('delivery_schedule', models.JSONField(blank=True, default=list, help_text='List of delivery milestones')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('terms', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_contracts_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_contracts', to='production.crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_contracts_as_farmer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
